# Generated by Django 5.2.6 on 2025-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(blank=True, max_length=150, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
