# Generated by Django 5.2.6 on 2025-10-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_agregado',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='libros_qr/'),
        ),
    ]
