# Generated by Django 5.2.6 on 2025-10-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_libro_descripcion_remove_libro_fecha_agregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
