# Generated by Django 5.2.6 on 2025-10-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
