# Generated by Django 5.2.6 on 2025-09-29 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(choices=[('avatar_pp1.jpeg', 'Avatar 1'), ('avatar_pp2.jpeg', 'Avatar 2'), ('avatar_pp3.jpeg', 'Avatar 3'), ('avatar_pp4.jpeg', 'Avatar 4')], default='avatar_pp1.jpeg', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
