"""
Django settings for shareclass project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url

# ==========================================
# CONFIGURACIÓN PRINCIPAL (Rutas con OS)
# ==========================================

# Usamos os.path para máxima compatibilidad en Railway
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# En local usa la string, en Railway busca la variable
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-o%9)x&k1)b#r^dru!@=$=p$@z8j8$*=8=sohm5^eu5!pwqhy$x')

# DEBUG: False en producción, True en local
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://*.up.railway.app']


# ==========================================
# APLICACIONES INSTALADAS
# ==========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  # Arriba de staticfiles
    'django.contrib.staticfiles',
    'cloudinary',
    
    # Tus Apps (Deben llamarse igual que las carpetas)
    'accounts',
    'libros', 
    'dispositivos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Vital para el CSS
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shareclass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shareclass.wsgi.application'


# ==========================================
# BASE DE DATOS (HÍBRIDA + SSL)
# ==========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'shareclass_db',
        'USER': 'shareclass_user',
        'PASSWORD': 'password_segura',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Configuración para Railway
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES["default"] = dj_database_url.parse(
        database_url,
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True,
    )


# ==========================================
# VALIDACIÓN Y OTROS
# ==========================================

AUTH_PASSWORD_VALIDATORS = [] # Relajado para desarrollo

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==========================================
# ARCHIVOS ESTÁTICOS (CONFIGURACIÓN BYPASS)
# ==========================================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Dónde buscar (Tus carpetas originales)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'accounts/static'),
    os.path.join(BASE_DIR, 'libros/static'),
    os.path.join(BASE_DIR, 'dispositivos/static'),
]

# --- LA MAGIA ESTÁ AQUÍ ---
# 1. Usamos el storage normal (sin compresión estricta)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# 2. IMPORTANTE: Le decimos a WhiteNoise que busque los archivos en tiempo real
# Esto evita que necesitemos el comando collectstatic que está fallando.
WHITENOISE_USE_FINDERS = True 
WHITENOISE_AUTOREFRESH = True

# ==========================================
# MEDIA / IMÁGENES (CLOUDINARY)
# ==========================================

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Almacenamiento de archivos en Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ==========================================
# LOGIN / LOGOUT
# ==========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'auth'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'auth'